INSERT INTO users (name, email, birth_date) VALUES ('Dr. Katrice Hahn', 'rudy.hermann@hotmail.com', '1994-10-11');
INSERT INTO users (name, email, birth_date) VALUES ('Lionel Harris', 'ricki.haag@hotmail.com', '1999-03-12');
INSERT INTO users (name, email, birth_date) VALUES ('Issac Gottlieb', 'tobias.hansen@yahoo.com', '1964-02-06');
INSERT INTO users (name, email, birth_date) VALUES ('Mr. Ayako Boyer', 'lavona.farrell@hotmail.com', '1953-04-15');
INSERT INTO users (name, email, birth_date) VALUES ('Mrs. Kareen Carroll', 'buck.crooks@hotmail.com', '1952-07-12');
INSERT INTO users (name, email, birth_date) VALUES ('Timmy Wuckert', 'loretta.ledner@yahoo.com', '1951-02-01');
INSERT INTO users (name, email, birth_date) VALUES ('Davina Christiansen', 'elli.predovic@hotmail.com', '1996-04-26');
INSERT INTO users (name, email, birth_date) VALUES ('Shaniqua Borer Sr.', 'gregg.kautzer@yahoo.com', '1979-04-15');
INSERT INTO users (name, email, birth_date) VALUES ('Cody Bernier', 'jesse.kunze@hotmail.com', '1963-02-21');
INSERT INTO users (name, email, birth_date) VALUES ('Asa Greenfelder DVM', 'demetrius.bogisich@yahoo.com', '2003-04-06');
INSERT INTO users (name, email, birth_date) VALUES ('Deirdre Schowalter', 'ozell.prosacco@hotmail.com', '1990-10-19');
INSERT INTO users (name, email, birth_date) VALUES ('Rosario Koepp', 'angelika.rippin@yahoo.com', '1990-12-11');
INSERT INTO users (name, email, birth_date) VALUES ('Georgianne Torp', 'chuck.cruickshank@yahoo.com', '1966-11-07');
INSERT INTO users (name, email, birth_date) VALUES ('Mrs. Diamond Schulist', 'serena.paucek@yahoo.com', '2005-06-04');
INSERT INTO users (name, email, birth_date) VALUES ('Lacey Balistreri', 'niki.grant@gmail.com', '1979-12-09');
INSERT INTO users (name, email, birth_date) VALUES ('Dr. Angel Hills', 'claudio.rowe@gmail.com', '1960-04-12');
INSERT INTO users (name, email, birth_date) VALUES ('Norberto Hayes', 'luis.collins@hotmail.com', '1991-12-06');
INSERT INTO users (name, email, birth_date) VALUES ('Mindi Bins', 'freddy.fay@yahoo.com', '1977-04-20');
INSERT INTO users (name, email, birth_date) VALUES ('Titus Friesen', 'laurena.medhurst@gmail.com', '1996-09-04');
INSERT INTO users (name, email, birth_date) VALUES ('Genoveva Bahringer Jr.', 'vance.rempel@yahoo.com', '1964-04-08');
INSERT INTO users (name, email, birth_date) VALUES ('Marylou Ernser DVM', 'alesha.hoppe@gmail.com', '1959-07-16');
INSERT INTO users (name, email, birth_date) VALUES ('Lynn Gutkowski Jr.', 'abigail.kunde@gmail.com', '1970-05-03');
INSERT INTO users (name, email, birth_date) VALUES ('Mrs. Reid Kiehn', 'wava.paucek@gmail.com', '2000-09-02');
INSERT INTO users (name, email, birth_date) VALUES ('Jordan Windler V', 'kristofer.gislason@hotmail.com', '1957-02-12');
INSERT INTO users (name, email, birth_date) VALUES ('Marshall Harber', 'darleen.torp@yahoo.com', '1997-12-10');
