INSERT INTO users (name, email, birth_date) VALUES ('Dr. Raylene Stanton', 'joshua.herman@yahoo.com', '1956-11-12');
INSERT INTO users (name, email, birth_date) VALUES ('Federico Turner', 'gilberto.hessel@gmail.com', '1987-08-19');
INSERT INTO users (name, email, birth_date) VALUES ('Jennine Goodwin', 'andy.bins@gmail.com', '1981-07-05');
INSERT INTO users (name, email, birth_date) VALUES ('Elmer Greenfelder', 'esta.bednar@gmail.com', '1956-06-18');
INSERT INTO users (name, email, birth_date) VALUES ('Bernie Rolfson', 'evelynn.cruickshank@gmail.com', '1996-04-16');
INSERT INTO users (name, email, birth_date) VALUES ('Jose Borer', 'jone.koch@gmail.com', '1971-02-13');
INSERT INTO users (name, email, birth_date) VALUES ('Elissa McClure', 'katy.hayes@hotmail.com', '1991-11-15');
INSERT INTO users (name, email, birth_date) VALUES ('Kendal Wunsch', 'aron.hammes@gmail.com', '1987-01-11');
INSERT INTO users (name, email, birth_date) VALUES ('Maria Windler', 'virgen.dickens@yahoo.com', '1971-01-17');
INSERT INTO users (name, email, birth_date) VALUES ('Martin Quitzon', 'arica.moore@gmail.com', '1996-10-07');
INSERT INTO users (name, email, birth_date) VALUES ('Willian Wisoky', 'lizbeth.stroman@gmail.com', '1995-10-22');
INSERT INTO users (name, email, birth_date) VALUES ('Ariana Hermann', 'vikki.kunde@hotmail.com', '1977-04-21');
INSERT INTO users (name, email, birth_date) VALUES ('Leandro Nolan', 'sheldon.gorczany@gmail.com', '2006-01-15');
INSERT INTO users (name, email, birth_date) VALUES ('Dr. Guy Feeney', 'leia.goldner@gmail.com', '1980-09-17');
INSERT INTO users (name, email, birth_date) VALUES ('Dr. Shawanda Waelchi', 'jospeh.mosciski@hotmail.com', '1951-09-10');
INSERT INTO users (name, email, birth_date) VALUES ('Alida Grant', 'josefa.adams@yahoo.com', '1986-01-29');
INSERT INTO users (name, email, birth_date) VALUES ('Nova Jaskolski', 'cristopher.goodwin@gmail.com', '1963-09-13');
INSERT INTO users (name, email, birth_date) VALUES ('Michelle Durgan', 'gillian.hackett@yahoo.com', '1970-06-30');
INSERT INTO users (name, email, birth_date) VALUES ('Mrs. Kyong Leannon', 'marisela.kunze@hotmail.com', '1955-04-19');
INSERT INTO users (name, email, birth_date) VALUES ('Mr. Forrest Strosin', 'leland.bahringer@hotmail.com', '1985-03-18');
INSERT INTO users (name, email, birth_date) VALUES ('Malik Mitchell', 'rudy.okuneva@hotmail.com', '1971-10-21');
INSERT INTO users (name, email, birth_date) VALUES ('Bess Cremin', 'toya.wunsch@yahoo.com', '2002-08-19');
INSERT INTO users (name, email, birth_date) VALUES ('Desmond Leffler', 'stacy.mccullough@hotmail.com', '1987-09-26');
INSERT INTO users (name, email, birth_date) VALUES ('Columbus Nitzsche', 'alethia.rowe@hotmail.com', '1964-07-05');
INSERT INTO users (name, email, birth_date) VALUES ('Kerry Haley', 'kris.hartmann@hotmail.com', '1950-07-07');
